services:
  quiz-game:

    build:
      context: ../../
      dockerfile: apps/quiz-game/Dockerfile

    container_name: quiz-game
    restart: unless-stopped
    ports:
      - "8083:80"
    environment:
      - NODE_ENV=production