services:
  cyber-chat:
    build:
      context: ../../
      dockerfile: apps/cyber-chat/Dockerfile
    container_name: cyber-chat-app
    restart: always
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0