services:
  art-gallery:
    build:
      context: ../../
      dockerfile: apps/art-gallery/Dockerfile
    container_name: art-gallery-app
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production